<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run()
    {
        $books = [
            // NOVEL TERE LIYE (10 buku)
            [
                'title' => 'Bumi',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2014,
                'category' => 'Fiksi',
                'stock' => 15,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Bulan',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2015,
                'category' => 'Fiksi',
                'stock' => 12,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Matahari',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2016,
                'category' => 'Fiksi',
                'stock' => 10,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Bintang',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2017,
                'category' => 'Fiksi',
                'stock' => 8,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Ceros dan Batozar',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2018,
                'category' => 'Fiksi',
                'stock' => 11,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Komet',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2018,
                'category' => 'Fiksi',
                'stock' => 9,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Nebula',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2019,
                'category' => 'Fiksi',
                'stock' => 7,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Selena',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2020,
                'category' => 'Fiksi',
                'stock' => 13,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Negeri Para Bedebah',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2012,
                'category' => 'Fiksi',
                'stock' => 6,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Rindu',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2014,
                'category' => 'Fiksi',
                'stock' => 14,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],

            // NOVEL VIRAL LAINNYA (5 buku)
            [
                'title' => 'Laut Bercerita',
                'author' => 'Leila S. Chudori',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'year' => 2017,
                'category' => 'Fiksi',
                'stock' => 8,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Critical Eleven',
                'author' => 'Ika Natassa',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2013,
                'category' => 'Fiksi',
                'stock' => 7,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Perahu Kertas',
                'author' => 'Dee Lestari',
                'publisher' => 'Bentang Pustaka',
                'year' => 2009,
                'category' => 'Fiksi',
                'stock' => 9,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Negeri 5 Menara',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2009,
                'category' => 'Fiksi',
                'stock' => 11,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],
            [
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'category' => 'Fiksi',
                'stock' => 20,
                'max_loan_days' => 14,
                'daily_fine' => 1000,
            ],

            // BUKU PEMROGRAMAN & TEKNOLOGI (15 buku)
            [
                'title' => 'Pemrograman Laravel Dasar',
                'author' => 'Dewi Aulia',
                'publisher' => 'Informatika Press',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 10,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Machine Learning Fundamentals',
                'author' => 'John Doe',
                'publisher' => 'Tech Publishing',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 5,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Data Science Handbook',
                'author' => 'Sarah Wilson',
                'publisher' => 'Data Press',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 3,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Web Development dengan React',
                'author' => 'Budi Santoso',
                'publisher' => 'Code Master',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 8,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Python untuk Pemula',
                'author' => 'Michael Chen',
                'publisher' => 'Programming House',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 12,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Algoritma dan Struktur Data',
                'author' => 'Prof. Ahmad Yani',
                'publisher' => 'Ilmu Komputer Press',
                'year' => 2021,
                'category' => 'Teknologi',
                'stock' => 6,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Database Management System',
                'author' => 'Lisa Wijaya',
                'publisher' => 'IT Publishing',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 7,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Mobile App Development dengan Flutter',
                'author' => 'Rizky Pratama',
                'publisher' => 'App Developer Press',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 4,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Cyber Security Fundamentals',
                'author' => 'David Smith',
                'publisher' => 'Security Publishing',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 5,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Artificial Intelligence Modern',
                'author' => 'Dr. Robert Brown',
                'publisher' => 'AI Research Press',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 3,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'JavaScript Advanced Programming',
                'author' => 'Sarah Johnson',
                'publisher' => 'Web Tech Publishing',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 9,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Cloud Computing dengan AWS',
                'author' => 'Alex Thompson',
                'publisher' => 'Cloud Experts',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 6,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'UI/UX Design Principles',
                'author' => 'Maria Garcia',
                'publisher' => 'Design Studio Press',
                'year' => 2022,
                'category' => 'Teknologi',
                'stock' => 8,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'DevOps Handbook',
                'author' => 'James Wilson',
                'publisher' => 'IT Operations Press',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 4,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
            [
                'title' => 'Blockchain Technology',
                'author' => 'Dr. Lee Min Ho',
                'publisher' => 'Future Tech Publishing',
                'year' => 2023,
                'category' => 'Teknologi',
                'stock' => 2,
                'max_loan_days' => 7,
                'daily_fine' => 2000,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }

        $this->command->info('30 buku berhasil ditambahkan!');
        $this->command->info('- 10 buku Tere Liye');
        $this->command->info('- 5 novel viral lainnya');
        $this->command->info('- 15 buku pemrograman & teknologi');
    }
}